[package]
name = "hecto"
version = "0.1.0"
authors = ["Busayo Famutimi <famutimi.busayo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2"
unicode-segmentation = "1"